"""add on delete cascade

Revision ID: e1490912e908
Revises: 2eb334db4587
Create Date: 2023-03-26 06:01:20.420387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1490912e908'
down_revision = '2eb334db4587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('note_owner_id_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_owner_id_fkey', 'note', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
